SuperHeroi/SuperHeroi.MVC/Controllers/UploadsController.cs
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web.Helpers;
using System.Web.Mvc;
using SuperHeroi.MVC.Models;

namespace SuperHeroi.MVC.Controllers
{
    public class UploadsController : Controller
    {
        public string DiretorioBase = "~/Upload/";
        public string DiretorioTemp = "~/Upload/Temp/";
        public string DiretorioCrop = "~/Upload/Crop/";

        [Authorize]
        public ActionResult Index()
        {
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var idUsuario = claimsIdentity.FindFirst(c => c.Type == "ClaimIdHeroi").Value;

                var dirUsuario = idUsuario + "/";
                var dir = Server.MapPath(DiretorioCrop + dirUsuario);
                if (Directory.Exists(dir))
                {
                    ViewBag.Arquivos = ListDiretory(dir);
                    ViewBag.Dir = DiretorioCrop.Replace("~", "..") + dirUsuario;
                }
            }

            return View();
        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Upload(object fileNameIdUsuario)
        {
            if (fileNameIdUsuario == null) throw new ArgumentNullException("fileNameIdUsuario");

            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                fileNameIdUsuario = claimsIdentity.FindFirst(c => c.Type == "ClaimIdUsuario").Value;

                //********************************************************/
                //Realiza o upload da imagem para um diretório temporário
                //para depois poder ser editada (recortada) e colocada no
                //local correto, depois a imagem temporário é liberada
                //********************************************************/

                //Captura a imagem
                var image = WebImage.GetImageFromRequest();

                //Verifica se a imagem foi capturada
                if (image != null)
                {
                    //Verifica o tamanho dela, se for maior que o determinado, reduz proporcionalmente
                    if (image.Width > 1110)
                    {
                        image.Resize(1110, ((1110 * image.Height) / image.Width));
                    }

                    //Nome do arquivo a ser salvo
                    var filename = fileNameIdUsuario + Path.GetExtension(image.FileName);

                    /**********/
                    //Diretório
                    /**********/
                    var dir = Server.MapPath(DiretorioTemp);
                    //verifica se o diretório já existe,
                    if (!Directory.Exists(dir))
                    {
                        //se o diretório não existe cria
                        Directory.CreateDirectory(dir);
                    }
                    else
                    {
                        //se o diretório existe, remove e cria novament
                        //(se assegura que não haverá outro arquivo no diretório temporário)
                        Directory.Delete(dir, true);
                        Directory.CreateDirectory(dir);
                    }


                    /**********/
                    //Arquivo
                    /**********/
                    image.Save(Path.Combine(dir, filename));
                    ViewBag.Filename = DiretorioTemp.Replace("~", "..") + filename;

                    return View();
                }
            }

            return View();
        }

        [HttpPost]
        public virtual ActionResult CropImage(string imagePath, int? cropPointX, int? cropPointY, int? imageCropWidth, int? imageCropHeight)
        {
            if (string.IsNullOrEmpty(imagePath)
                || !cropPointX.HasValue
                || !cropPointY.HasValue
                || !imageCropWidth.HasValue
                || !imageCropHeight.HasValue)
            {
                return new HttpStatusCodeResult((int)HttpStatusCode.BadRequest);
            }

            //Arquivo
            var imageBytes = System.IO.File.ReadAllBytes(Server.MapPath(imagePath));
            //Imagem editada (recortada)
            var croppedImage = ImageHelper.CropImage(imageBytes, cropPointX.Value, cropPointY.Value, imageCropWidth.Value, imageCropHeight.Value);
            //Nome do arquivo
            var fileName = Path.GetFileNameWithoutExtension(imagePath);
            /**********/
            //Diretório
            /**********/
            var dir = Server.MapPath(DiretorioCrop + fileName + "/");
            //path é o caminho da imagem cortada
            var path = "";
            //verifica se o diretório já existe,
            if (!Directory.Exists(dir))
            {
                //se o diretório não existe cria
                Directory.CreateDirectory(dir);
                var nomeFile = fileName + ".1" + Path.GetExtension(imagePath);

                /**********/
                //Arquivo
                /**********/
                FileHelper.SaveFile(croppedImage, Path.Combine(dir, nomeFile));

                //Exclui temporário
                var dirTemp = Server.MapPath(DiretorioTemp);
                //verifica se o diretório ainda existe, e remove
                if (Directory.Exists(dirTemp))
                {
                    Directory.Delete(dirTemp, true);
                }

                path = DiretorioCrop + fileName + "/" + nomeFile;
            }
            else
            {
                for (int i = 1; i < 11; i++)
                {
                    var nomeFile = fileName + "." + i + Path.GetExtension(imagePath);

                    if (!System.IO.File.Exists(dir + nomeFile))
                    {
                        /**********/
                        //Arquivo
                        /**********/
                        FileHelper.SaveFile(croppedImage, Path.Combine(dir, nomeFile));

                        //Exclui temporário
                        var dirTemp = Server.MapPath(DiretorioTemp);
                        //verifica se o diretório ainda existe, e remove
                        if (Directory.Exists(dirTemp))
                        {
                            Directory.Delete(dirTemp, true);
                        }

                        path = DiretorioCrop + fileName + "/" + nomeFile;

                        break;
                    }
                }
            }

            return Json(new { photoPath = path.Replace("~", "..") }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(string fileName)
        {
            var claimsIdentity = User.Identity as ClaimsIdentity;
            if (claimsIdentity != null)
            {
                var idUsuario = claimsIdentity.FindFirst(c => c.Type == "ClaimIdUsuario").Value;

                var dir = Server.MapPath(DiretorioCrop + idUsuario);
                var image = Path.Combine(dir, fileName);

                if (System.IO.File.Exists(image))
                {
                    System.IO.File.Delete(image);
                }

                // se não houver arquivos no diretório, remove-o
                if (!ListDiretory(dir).Any())
                {
                    Directory.Delete(dir, true);
                }
            }

            return RedirectToAction("Index");
        }

        public FileInfo[] ListDiretory(string dir)
        {
            //Marca o diretório a ser listado
            var diretorio = new DirectoryInfo(dir);

            //Executa função GetFile(Lista os arquivos desejados de acordo com o parametro)
            var arquivos = diretorio.GetFiles("*.*");

            return arquivos;
        }
    }
}

SuperHeroi/SuperHeroi.MVC/Views/Uploads/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Upload", "Upload")
</p>

<div class="row">
    @{
        if (ViewBag.Arquivos != null)
        {
            foreach (var item in ViewBag.Arquivos)
            {
                <div class="col-xs-2">
                    <a href="#" class="thumbnail">
                        <img src="@ViewBag.Dir@item.Name" class="img-responsive" alt="" />
                        @Html.ActionLink("Remover", "Delete", "Uploads", new { fileName = item.Name }, null)
                    </a>
                </div>
            }
        }
    }
</div>

SuperHeroi/SuperHeroi.MVC/Views/Uploads/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}

<h2>Upload</h2>

<p><a href="#" id="hl-crop-image">Crop Image</a></p>


@using (Html.BeginForm("Upload", "Uploads", FormMethod.Post, new { @encType = "multipart/form-data" }))
{
    <input type="file" name="img" />

    <input type="submit" name="submit" value="upload" />
}

@if (ViewBag.Filename != null)
{
    <img id="my-origin-image" src="@ViewBag.Filename" alt="" />
}

<p>
    <img id="my-cropped-image" src="#" style="display:none;" alt="" />
</p>



@section scripts{
    <script type="text/javascript">

        var imageCropWidth = 0;
        var imageCropHeight = 0;
        var cropPointX = 0;
        var cropPointY = 0;

        $(document).ready(function () {
            initCrop();
        });

        $("#hl-crop-image").on("click", function (e) {
            e.preventDefault();
            cropImage();
        });

        function initCrop() {
            $('#my-origin-image').Jcrop({
                onChange: showCoords,
                bgColor: 'black',
                bgOpacity: .4,
                aspectRatio: 4 / 3,
                minSize: [555, 415],
                maxSize: [555, 415],
                setSelect: [277, 250, 555, 415]
            });
        }

        function showCoords(e) {

            imageCropWidth = e.w;
            imageCropHeight = e.h;

            cropPointX = e.x;
            cropPointY = e.y;
        }

        function cropImage() {

            if (imageCropWidth == 0 && imageCropHeight == 0) {
                alert("Por favor, selecione uma área de corte.");
                return;
            }

            imageCropWidth = parseInt(imageCropWidth);
            imageCropHeight = parseInt(imageCropHeight);

            $.ajax({
                url: '/Uploads/CropImage',
                type: 'POST',
                data: {
                    imagePath: $("#my-origin-image").attr("src"),
                    cropPointX: cropPointX,
                    cropPointY: cropPointY,
                    imageCropWidth: imageCropWidth,
                    imageCropHeight: imageCropHeight
                },
                success: function (data) {
                    $("#my-cropped-image")
                        .attr("src", data.photoPath)
                        .show();
                    $("#my-origin-image").Jcrop(
                        destroy()
                    );
                },
                error: function (data) { }
            });
        }
    </script>
}